FROM postgres:15

# Install the postgresql debugger
RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y --no-install-recommends postgresql-15-pldebugger

EXPOSE 5432